### ISSUE TITLE
name 's_dist' is not defined

### ISSUE THREAD

**Issue by AsadTanvir** [timothyjamesbecker/transit_alignment#1] opened 2022-06-05 20:22 UTC
After preprocessing the network, when **search.py** is run it's showing

> error encountered with C[i]= [.............................]]
> name 's_dist' is not defined 

The tsv file in output folder is blank. There are also not any pickle files generated in the output. Do we need to add this **‘s_dist’** parameter somewhere in the RTS_FULL function?
@timothyjamesbecker

**Comment by timothyjamesbecker** [comment] 2022-06-13 14:20
You would need to provide more details in order for anything to be discovered about your issue.  Please spend some time to read about how to set up a reproducible issue : https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f.  I am closing this issue since there is not enough information.

**Closed as completed by timothyjamesbecker** 2022-06-13 14:20 UTC
